### ISSUE TITLE
fix: coverage_excludes not working for Dart packages

### ISSUE THREAD

**Issue by arturograu** [VeryGoodOpenSource/very_good_workflows#139]
**Description**
Seems that the coverage_excludes is not working for Dart packages.
For example I have this in my GitHub workflow file:

```
build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      coverage_excludes: '*.freezed.dart'
      dart_sdk: 'stable'
```

But then the coverage on the GitHub action shows that I don't have these lines covered:
```
/home/runner/work/my_api_client_library/my_api_client_library/lib/src/models/config_file_record/config_file_record.freezed.dart: 12, 14, 23, 24, 26, 27, 29, 44, 51, 57, 59, 63, 85, 87, 89, 95, 97, 101, 121, 123, 135, 137, 139, 143, 165, 168
  - /home/runner/work/my_api_client_library/my_api_client_library/lib/src/models/config_files_response/config_files_response.freezed.dart: 12, 14, 23, 24, 26, 27, 29, 44, 51, 57, 59, 63, 85, 87, 89, 95, 97, 101, 130, 132, 145, 147, 148, 150, 154, 177, 180
```

**Steps To Reproduce**

1. Create a Dart library with very_good_cli.
2. Add the coverage_excludes setting to the GitHub workflow
3. Push the code to GitHub to check if the files are ignored

**Expected Behavior**
It's expected to pass the coverage GitHub action without testing the ignored files.
