### ISSUE TITLE
fix: Cannot exclude generated files from "Check Formatting"

### ISSUE THREAD

**Issue by rekire** [VeryGoodOpenSource/very_good_workflows#170]
**Description**
I'm testing your workflow and have no problems with generated dart code. How can I exclude that files from the "Check Formatting" step?

**Steps To Reproduce**

1. Generate some files with e.g. too long lines
2. Check failes

**Expected Behavior**
A way to exclude generated files with patterns like `coverage_excludes: '*.g.dart *.freezed.dart'`

**Screenshots**
No.

**Additional Context**
Nope²

**Comment by alestiago** [comment]
Hi @rekire 👋 ! Thanks for opening an issue!

As far as I know there is no explicit way to "exclude directories from being formatted". Instead, you'll have to use `format_directories` and outline those that you would like to be formatted, see the[ Very Good Workflows `format_directories` documentation](https://workflows.vgv.dev/docs/workflows/flutter_package#format_directories).

Here is a Dart issue https://github.com/dart-lang/dart_style/issues/864 related to what you're asking. 

Here's an example of `format_directories`:
```yaml
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/my_app
      format_directories: "lib test"
```

On our end we could potentially wrap around and provide such feature, a feature as such would have to be triaged and evaluated by the team to see if we should have such feature, how we should go around it and how much of a priority it is. I'll add this to _Triage_ and let you know what the team decides to move forward with this 🙌 .

Let me know if this helps 💙
