### ISSUE TITLE
could not load the saved OAuth2 credentials

### ISSUE THREAD

**Issue by bandinopla** [VeryGoodOpenSource/very_good_workflows#172]
**Description**
Action fails to run because it can't load the credentials:

```bash
Warning: could not load the saved OAuth2 credentials.
Obtaining new credentials...
Pub needs your authorization to upload packages on your behalf.
```

I'm running this workflow:
```yaml
jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_pub_publish.yml@v1
    with: 
      pub_credentials: secrets.PUB_CREDENTIALS
```
in PUB_CREDENTIALS y copy & pasted the contents of `pub-credentials.json`

https://workflows.vgv.dev/docs/workflows/flutter_pub_publish#example-usage

**Comment by amanxnanda** [comment]
+1

**Comment by Goddchen** [comment]
Also using `${{ secrets.PUB_CREDENTIALS }}` doesn't work.

**Comment by alestiago** [comment]
Pinging you here @wolfenrain

**Comment by KeidsID** [comment]
It needs base64 support on credentials to make it work:

```yml
name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    defaults:
      run:
        working-directory: "."

    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        flutter-version: [3.10.x]
        flutter-channel: [stable]

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.flutter-channel }}
          cache: true

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: 🔐 Setup Pub Credentials
        run: |
          mkdir -p $XDG_CONFIG_HOME/dart
          echo '${{secrets.PUB_CREDENTIALS}}' | base64 --decode > "$XDG_CONFIG_HOME/dart/pub-credentials.json"

      - name: 🌵 Dry Run
        run: flutter pub publish --dry-run

      - name: 📢 Publish
        run: flutter pub publish -f

```
