### ISSUE TITLE
Unable to setup workflow for sub directory

### ISSUE THREAD

**Issue by YadavGulshan** [VeryGoodOpenSource/very_good_workflows#20]
**Description**
I'm trying to setup a workflow for my [project](https://github.com/YadavGulshan/MedAlthea) which contains multiple projects. One of them was flutter. I checked the readme of very_good_workflow which states that `working_directory` can help me with running this workflow in sub directory.

**Steps To Reproduce**
```yaml
name: medalthea

on: [pull_request, push]

env:
  working_directory: "./medalthea/."

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 2.10.0
```
I tried "./medalthea", "medalthea", etc but none of them worked.

**Expected Behavior**
I just want to make this workflow to work in my flutter project dir.

**Screenshots**
![image](https://user-images.githubusercontent.com/63960580/160844516-6361eb85-3378-43a8-9fc7-a8ec698d24dc.png)
