### ISSUE TITLE
feat: custom linting (more than 80 lines for formatting)

### ISSUE THREAD

**Issue by tomassasovsky** [VeryGoodOpenSource/very_good_workflows#21]
It would be nice for the build not to fail if the code is not formatted like the Dart linter suggests.

Is there any way to change this?

**Comment by wolfenrain** [comment]
While I personally would not recommend it, as Dart and the IDE tooling for the language always come with the `80 char line` rule, I do see the added value for companies that have their own configuration for this.

Sadly there is currently no way to do this using the `analysis_options.yaml` file. But the `flutter format` command does expose a `--line-length int` flag.  So we could add a `--line-length ${{inputs.line_length}}` flag to the step.?

What do you think @felangel?

**Comment by Luckey-Elijah** [comment]
Would greatly appreciate a feature to allow a custom line length passed to the dart/flutter format command. Something like:
```yaml
jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: packages/my_package
      line_length: 100 # adding this option
      min_coverage: 100
```
