### ISSUE TITLE
feat: Execute workflow in multiple working directories

### ISSUE THREAD

**Issue by renancaraujo** [VeryGoodOpenSource/very_good_workflows#31]
## The problem(s)

As a developer with multiple packages in the same repository, it is necessary to create a new workflow for each new repository
It is also necessary manually configure each these workflows with the right `on` triggers to filter workflow runs. 
On top that, if a package has any local path dependency, it is necessary to manually map these dependencies to run the workflow whenever they change.

This is error prone and it is difficult to keep different files standardized.

1. Multiple similar workflow files on repositories with multiple packages
2. For each workflow, it should contain an "on" trigger to prevent the workflow to run unnecessarily
3. It is not easy to manually map and keep updated a list of local dependencies for each workflow

### 1. Using matrix

In this proposal, packages with multiple dart and flutter packages would have a single top workflow (just like the existing ones) and would optionally receive multiple paths in the `working_directory` field. Then the very_good_workflow would take care of creating steps dynamically.

Usage example on a workflow for dart sub packages

```yaml
jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
      dart_sdk: "stable"
      working_directory: examples/my_dart_package examples/my_other_dart_package
      
      # or
      
      working_directory: "["examples/my_dart_package ", "examples/my_other_dart_package" ]" 
``` 

For crating steps for each passed workflow we should use matrix.  See [discussion](https://github.community/t/reusable-workflow-with-strategy-matrix/205676). 

### 2. Using multiple workflow files

Here, sub packages would heave each its own `.github/workflows` structure. This would require the following changes:

- `very_good_core` would include a noop job for eventual sub packages to serve as an example;
- `dart_pkg` and `flutter_pkg` templates for `very_good create` would include a `.github/workflows` structure with workflow ready to be called by a top workflow;
- A new root very_good_workflow would check for any eventual subpackage (under `/packages` or any dir with a `pubspec.yaml` file, to be discussed) and warn for the absence of a workflow for them (unless a specific directory is explicitly ignored).

## About restricting runs

I believe that regardless of which hypothesis is chosen, restricting workflow runs for a sub package has its own value.

1. Add an optional input to restrict workflow runs. 
```yaml
jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
      dart_sdk: "stable"
      # restrict runs
      restrict_runs: true # or "true" 
``` 
Then we could restrict runs to only when the package path has changed.
2. For the problem of internal dependencies, investigate how the output of `flutter pub deps` could help us here.

**Comment by renancaraujo** [comment]
So after a little research on thesedifferent approaches, where we go:

## The status QUO

Here at VGV we follow the pattern of having a parent package (always a Flutter app) and sub packages under `/packages`. These sub packages may depend on one another. 

```
<repository root (flutter app)>
| - .github/
    | - workflows/
        | - root_package.yaml
        | - sub_package_1.yaml
        | - sub_package_2.yaml
        | - sub_package_3.yaml
        | - sub_package_4.yaml
        | - sub_package_5.yaml
| - packages/
    | - sub_package_1
    | - sub_package_2
    | - sub_package_3
    | - sub_package_4
    | - sub_package_5
 ...
```

For each new subpackage, it must be manually created a workflow for it. Like this:

```yaml
name: sub_package_1

# path filters
on:
  pull_request:
    paths:
      - "packages/sub_package_1/**"
      - ".github/workflows/sub_package_1.yaml"
  push:
    branches:
      - main
    paths:
      - "packages/sub_package_1/**"
      - ".github/workflows/sub_package_1.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      coverage_excludes: "**/*.g.dart"
      dart_sdk: "stable"
      working_directory: "packages/sub_package_1"
```


## 1. Using matrix


```
<repository root (flutter app)>
| - .github/
    | - workflows/
        | - root_package.yaml
        | - dart_pkg_workflows.yaml
        | - flutter_pkg_workflows.yaml
| - packages/
    | - sub_package_1
    | - sub_package_2
    | - sub_package_3
    | - sub_package_4
    | - sub_package_5
 ...
```


### What changes:

When using the approach for a matrix run, we would not need for a workflow file for each sub package. But instead, each package should be disclosed in an unified workflow file. 

Inside our workflows, we would have to dynamically create steps given that matrix f paths. 


### Pros ✅:
- Little setup required for repos using very_good_worflows today
- The infra-structure of packages 

### Cons ❌:
- Reusable workflows cannot receive lists as parameter. As a result, the input would have to have a very specific JSON-like format:  `"["packages/sub_package_1 ", "packages/sub_package_2" ]"`
- When creating a a new sub package, the user still needs to remember to disclose that package in the workflow. Not much change from creating a workflow file
- Using GitHub's path filters becomes more ineffective as more sub packages are added to the input, dynamic restrict runs would HAVE to be implemented before adopting this approach.
 - The user still has to create separate workflows for flutter and dart packages. Little to no effect on repos with fewer packages. 


## 2. Using multiple workflow files


```
<repository root (flutter app)>
| - .github/
    | - workflows/
        | - root_package.yaml
        | - package_check_workflow.yaml
        | - sub_package_1.yaml
        | - sub_package_2.yaml
        | - sub_package_3.yaml
        | - sub_package_4.yaml
        | - sub_package_5.yaml
| - packages/
    | - sub_package_1
        | - .github/
            | - workflows/
                | - sub_package_1.yaml
    | - sub_package_2
        | - .github/
            | - workflows/
                | - sub_package_2.yaml
    | - sub_package_3
        | - .github/
            | - workflows/
                | - sub_package_3.yaml
    | - sub_package_4
        | - .github/
            | - workflows/
                | - sub_package_4.yaml
    | - sub_package_5
        | - .github/
            | - workflows/
                | - sub_package_5.yaml
 ...
```

### What changes:

Each sub packages is self sufficient, containing its necessary workflow. For each sub package, a workflow file would point to the one inside the packages via the keyword `uses`.

This can be expanded by automate the creation of the inner workflows by including them on the `very_good create` template bundles (dart_pkg and flutter_pkg).

A further step would also include a top workflow `package_check_workflow.yaml` that scans for sub packages without dedicated workflows in the root. 

### Pros ✅:
- Each sub package could be extracted from the monorepo without much hassle
- More room for automation when including the creation of sub workflow files via `very_good create --template`

### Cons ❌:
- This creates a complex infra structure of workflow files across the repo as more sub packages are added. 
- Requires more changes in projects currently using `very_good_workflows`.
- If any of the sub packages is a federated plugin, would this mean that each platform package would require its own workflow file? Things can get very complex here
- Not improvement from the status quo when it comes down to the amount of workflow files in the root
-Steep learning curve for people outside VGV where patterns for sub packages may be different.
