### ISSUE TITLE
feat: add report_on flag to flutter package

### ISSUE THREAD

**Issue by marcossevilla** [VeryGoodOpenSource/very_good_workflows#319]
### Description

Currently the `flutter_package` workflow doesn't have any `report_on` parameter like `dart_package` does:
```yaml
report_on:
        required: false
        type: string
        default: "lib"
```
This is useful since due to [Pub Workspaces](https://dart.dev/tools/pub/workspaces) we now have to use `flutter_package` in CI because it uses `flutter pub get` by default, so this makes it easier to set custom folders on Dart-only packages to report to coverage.

### Requirements

- [x] All CI/CD checks are passing.
- [x] There is no drop in the test coverage percentage.
