### ISSUE TITLE
fix: workflow fails with FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by orestesgaolin** [VeryGoodOpenSource/very_good_workflows#33]
**Description**

When using dart_package workflow, the tests fail to collect coverage.

```
Run dart test --coverage=coverage && dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

✅ test/src/confirm_email_test.dart: ConfirmEmail constructors pure creates correct instance
....
✅ test/src/email_test.dart: Email validator is valid when email is valid

🎉 2[7](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:7:7) tests passed.
Unhandled exception:
FormatException: Unexpected character (at character 1)
# This file is deprecated. Tools should instead consume 
^

#0      throwError (package:package_config/src/errors.dart:32:35)
#1      parsePackageConfigString (package:package_config/src/package_config_json.dart:54:12)
#2      PackageConfig.parseString (package:package_config/src/package_config.dart:94:7)
#3      Resolver._parsePackages (package:coverage/src/resolver.dart:115:23)
#4      Resolver.create (package:coverage/src/resolver.dart:34:13)
#5      HitMap.parseJson (package:coverage/src/hitmap.dart:45:37)
#6      HitMap.parseFiles (package:coverage/src/hitmap.dart:173:41)
#7      main (file:///home/runner/.pub-cache/hosted/pub.dartlang.org/coverage-1.3.0/bin/format_coverage.dart:66:31)
#[8](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:7:8)      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:2[9](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:7:9)5:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:[12](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:7:12))
Error: Process completed with exit code [25](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:7:25)5.
```

**Additional Context**

Workflow:

```
name: form_inputs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/form_inputs/**"
      - ".github/workflows/form_inputs.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
      dart_sdk: "stable"
      working_directory: "packages/form_inputs"
```

Job setup:

```
Current runner version: '2.291.1'
Operating System
  Ubuntu
  [2](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:1:2)0.04.4
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 2022050[3](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:1:3).1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220503.1/images/linux/Ubuntu200[4](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:1:4)-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220[5](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:1:5)03.1
Virtual Environment Provisioner
  1.0.0.0-main-20220421-1
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:7884fcad[6](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:1:6)b5d53d10323aee[7](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:1:7)24dc6[8](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:1:8)d8b[9](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:1:9)096a2e)
Download action repository 'dart-lang/setup-dart@v1' (SHA:6a218f2413a3e78e9087f638a238f6b40893203d)
Download action repository 'VeryGoodOpenSource/very_good_coverage@v1' (SHA:feed99cc060453828a8f[12](https://github.com/org/repo/runs/6402844755?check_suite_focus=true#step:1:12)e74b404baace8e4502)
```
