### ISSUE TITLE
fix: Action breaks when flutter_version is not informed

### ISSUE THREAD

**Issue by tyemy** [VeryGoodOpenSource/very_good_workflows#56]
**Description**
In the documentation `flutter_version` is optional but when is not informed `Setup Flutter` step fails.

**Steps To Reproduce**

1. Add a workflow using `flutter_package.yml`
2. Do not inform `flutter_version`
3. See error

Example:
```
jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
      test_recursion: true
```

**Screenshots**

<img width="1115" alt="Screen Shot 2022-07-11 at 21 53 53" src="https://user-images.githubusercontent.com/7231979/178384914-d92c2578-1050-4d77-a77f-69f09e33fb10.png">
