### ISSUE TITLE
docs: workflow optimization suggestions

### ISSUE THREAD

**Issue by PlugFox** [VeryGoodOpenSource/very_good_workflows#8]
Hello, at this [line](https://github.com/VeryGoodOpenSource/very_good_workflows/blob/main/.github/workflows/ci.yml#L8) you may use [`path:`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-including-paths) or `path-ignore:` to exclude code check if nothing changed.

You can add `workflow_dispatch:` to make available manual pipeline launching.
And you can use pattern matching with glob syntax for branches
Also can add some useful parameters for every job, e.g:
```yml
name: CLIENT / CHECKOUT

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'support/**'
    paths:
      - 'client/lib/**.dart' # <== PIPELINE RUNNING ONLY ON PUSH IF CODE CHANGED
  pull_request:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'support/**'
    paths:
      - 'client/lib/**.dart' # <== PIPELINE RUNNING ONLY ON PR IF CODE CHANGED
  workflow_dispatch: # <== MANUAL RUN

jobs:
  check-client:
    name: 'Checkout client'  # <== NAME
    timeout-minutes: 5  # <== TIMEOUT
    runs-on: ubuntu-latest
    container:
      image: plugfox/flutter:beta # <== ALPINE FLUTTER VERSION, ONLY 35 MB
      options: --user root
    env:
      working-directory: ./client # monorepo with dart code inside "client" directory
    steps:
      - name: 🚂 Get the latest code
        uses: actions/checkout@v2

      - name: 🚃 Cache pub modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pub-modules
        with:
          path: |
            $PWD/.pub_cache/
          key: ${{ runner.os }}-dart

      - name: 🗄️ Export pub cache directory
        run: export PUB_CACHE=$PWD/.pub_cache/

      - name: 🚚 Get dependencies
        working-directory: ${{ env.working-directory }}
        run: |
          flutter pub get \
            && flutter pub global activate **intl_utils**

      - name: 🏗️ Codegen
        working-directory: ${{ env.working-directory }}
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs --release ; \
          flutter pub global run intl_utils:generate
          
      - name: ✔️ Check sources with analyzer
        working-directory: ${{ env.working-directory }}
        run: |
          flutter analyze --no-pub --current-package --congratulate \
            --current-package --no-fatal-infos --fatal-warnings \
            --no-preamble --write=analyze.txt
            
      - name: 📁 Upload result
        uses: actions/upload-artifact@v2
        with:
          name: test
          if-no-files-found: ignore
          retention-days: 7
          path: |
            client/analyze.txt
```

You can improve your flutter/dart code with aditional linter rules from [dart-code-metrics](https://github.com/dart-code-checker/dart-code-metrics)
And their action for CI: [dart-code-metrics-action](https://github.com/dart-code-checker/dart-code-metrics-action)

**Comment by felangel** [comment]
Hi @PlugFox 👋
Thanks for opening an issue!

I’m not sure I understand the request. All of your suggestions are great and you can already make use of most of them in a workflow that uses very_good_workflows. 

For example:

```yaml
name: my_package

on:
  pull_request:
    paths:
      - "/packages/my_package/**"
      - ".github/workflows/my_package.yaml"
  workflow_dispatch:

jobs:
  build:
    uses: VGVentures/very_good_start/.github/workflows/dart_package.yaml@ci/reusable-workflows
    with:
      working_directory: packages/my_package
```

For more project specific checks (dart code metrics) feel free to fork this workflow and customize it for your own needs 👍

Let me know if that helps and thanks!
